// flow-typed signature: db945119c2ce2be9f93535fed4e3c80c
// flow-typed version: <<STUB>>/apollo-server-koa_v^1.3.6/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-server-koa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-server-koa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-server-koa/dist/index' {
  declare module.exports: any;
}

declare module 'apollo-server-koa/dist/koaApollo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-server-koa/dist/index.js' {
  declare module.exports: $Exports<'apollo-server-koa/dist/index'>;
}
declare module 'apollo-server-koa/dist/koaApollo.js' {
  declare module.exports: $Exports<'apollo-server-koa/dist/koaApollo'>;
}
